Fixed many typos
cc65/cc65 pull request #1618
Opened 2021-12-22 08:52 UTC by polluks2

2021-12-22 16:36 UTC, WayneParham commented
Good catches, thanks!

2021-12-22 17:52 UTC, polluks commented
@WayneParham It was a Codespell job.

2022-01-29 20:34 UTC, mrdudz requested changes
please remove the code changes from this PR

2022-01-29 20:34 UTC, mrdudz commented on libsrc/cbm/read.s
> +        .byte   $2C             ; Skip next opcode
this shouldnt be part of this PR

2022-01-29 20:34 UTC, mrdudz commented on libsrc/cbm/write.s
> +        .byte   $2C             ; Skip next opcode
this shouldnt be part of this PR

2022-01-30 02:41 UTC, polluks approved these changes
done

2022-01-30 11:21 UTC, merged