Expand KIM-1 samples with graphics primitives, text, etc
cc65/cc65 pull request #2194
Opened 2023-09-16 17:24 UTC by davepl

This checkin extends the set of KIM-1 samples with a number of graphics primitives targeting the MTU K-1008 Visible Memory board.

Includes pixel, linedraw, circle, moire, and Conway's Game of Life in C.

2023-09-21 19:23 UTC, mrdudz commented on .gitignore
Please remove the changes to .gitignore from this PR

2023-10-08 11:52 UTC, mrdudz commented on .gitignore
Hello? :)

2023-10-14 21:19 UTC, mrdudz commented
You might want to set your editor to automatically remove spaces at the end of each line...

So is this ready for merging?

2023-10-14 21:33 UTC, mrdudz commented
hrm and there are TABs too... please fix :)

2023-10-16 17:15 UTC, mrdudz requested changes
Please remove the binaries and object files that do not belong into the repository

2023-10-16 17:15 UTC, mrdudz commented on samples/kim1/kimHello.bin
This file should be removed from the PR

2023-10-16 17:15 UTC, mrdudz commented on samples/kim1/kimLife.bin
This file should be removed from the PR

2023-10-16 17:15 UTC, mrdudz commented on samples/kim1/kimSieve.bin
This file should be removed from the PR

2023-10-16 17:15 UTC, mrdudz commented on samples/kim1/kimTest.bin
This file should be removed from the PR

2023-10-16 17:15 UTC, mrdudz commented on samples/kim1/ramfont.o
This file should be removed from the PR

2023-10-16 17:15 UTC, mrdudz commented on samples/kim1/subs.o
This file should be removed from the PR

2023-10-16 17:15 UTC, mrdudz commented on samples/kim1/font.rom
What is this file good for? It seems like this one should also be removed from this PR.

2023-10-16 17:38 UTC, mrdudz commented
I fixed the codestyle issues, still those .o and .bin files should be removed. Apparently i cant remove them from the PR.

2023-10-16 20:05 UTC, polluks commented
How about including *.lst and so on in .gitignore?

2023-10-16 20:11 UTC, mrdudz commented
> How about including *.lst and so on in .gitignore?

I might do that later in selected directories. It's not the solution for this problem though :)

2023-10-16 20:57 UTC, davepl commented
Thanks for the cleanup, and sorry for the mess!  Just FWIW, I had those in a local .gitignore that I was asked to remove, so did, and didn’t want to monkey with the root one.  The makefile should clean them already, and of course they should not be checked in…

- Dave

> On Oct 16, 2023, at 1:11 PM, Bob Andrews ***@***.***> wrote:
> 
> 
> How about including *.lst and so on in .gitignore?
> 
> I might do that later in selected directories. It's not the solution for this problem though :)
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/cc65/cc65/pull/2194#issuecomment-1765196983>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AA4HCFY7XQHB46OZZESWFGLX7WIG7AVCNFSM6AAAAAA43ASDDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONRVGE4TMOJYGM>.
> You are receiving this because you authored the thread.
>

2023-10-16 21:13 UTC, mrdudz commented
> Thanks for the cleanup, and sorry for the mess! Just FWIW, I had those in a local .gitignore that I was asked to remove, so did, and didn’t want to monkey with the root one. The makefile should clean them already, and of course they should not be checked in… - Dave

If you could just make a commit that removes those files... then i can merge :) No idea why the github interface allows me to remove textfiles no problem, but not binaries. weird.

2023-10-16 22:51 UTC, mrdudz commented
So, what about font.rom?

2023-10-17 00:07 UTC, davepl commented
That’s a binary of the font itself, and should remain in the project ideally.  The source contains an encoded version of it, but it comes in handy if that needs to be recreated.

- Dave

> On Oct 16, 2023, at 3:51 PM, Bob Andrews ***@***.***> wrote:
> 
> 
> So, what about font.rom?
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/cc65/cc65/pull/2194#issuecomment-1765390681>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AA4HCF7QRUTAAELFNO7YFDDX7W26RAVCNFSM6AAAAAA43ASDDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONRVGM4TANRYGE>.
> You are receiving this because you authored the thread.
>

2023-10-17 08:06 UTC, mrdudz commented
> That’s a binary of the font itself, and should remain in the project ideally. The source contains an encoded version of it, but it comes in handy if that needs to be recreated. - Dave

I see. It would be great if you could describe the samples added with this PR in samples/readme.txt in a similar way the other samples are being described.

2023-10-22 15:14 UTC, mrdudz commented
> I see. It would be great if you could describe the samples added with this PR in samples/readme.txt in a similar way the other samples are being described.

@davepl would you? And please keep an eye on those codestyle issues. (you can always use "make checkstyle" to find those)

2023-11-12 17:19 UTC, mrdudz commented
@davepl So?

It also might be a good idea not to keep committing into a PR once its "green" - if you can't keep it clean from breaking codestyle issues for whatever reason :)

2023-12-06 00:04 UTC, mrdudz commented
*ping*

2024-01-23 22:50 UTC, mrdudz commented
@davepl so what's up with this?

2024-01-23 23:05 UTC, davepl commented
Sorry, I've been very busy and this is a little ways down the list of todos, but realize I left it unfinished.  Sorry for the inconvenience!  It all compiled and worked, but didn’t meet the project requirements, which is entirely my bad.

If you can can give me two pieces of information it would assist me in resolving it more promptly:

- What git clone command do I need to get get a current snapshot of the PR so I can revise it?
- What remains to be done other than the gitignore? I can likely do that much directly

Thanks,
Dave


> On Jan 23, 2024, at 2:50 PM, Bob Andrews ***@***.***> wrote:
> 
> 
> @davepl <https://github.com/davepl> so what's up with this?
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/cc65/cc65/pull/2194#issuecomment-1907050013>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AA4HCF6MHXYH4EK6GPHZSLLYQA5DPAVCNFSM6AAAAAA43ASDDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBXGA2TAMBRGM>.
> You are receiving this because you were mentioned.
>

2024-01-24 10:57 UTC, rofl0r commented
the current PR is broken, thanks to the merge commits in between. never ever merge branches into a branch that's the basis for a PR. i went ahead and fixed the contents of this PR using my advanced git-fu into this single patch with is stripped of the binaries: https://0x0.st/HGj5.patch

to move forward, clone the latest master from here, create a new branch KIMList2 or whatever, and then apply above patch with git am filename.patch, then add what's been requested in another commit, and push it to github.
the outstanding request is this comment: https://github.com/cc65/cc65/pull/2194?notification_referrer_id=NT_kwDOAAU1sbE3NzQyODMzNDMzOjM0MTQyNQ#issuecomment-1765887453

@mrdudz: if you merge this PR as-is, the commit history of cc65 will be broken for eternity

2024-01-24 13:43 UTC, mrdudz commented
> never ever merge branches into a branch that's the basis for a PR.

>  if you merge this PR as-is, the commit history of cc65 will be broken for eternity

No idea what you mean - i have been doing this all the time with the fptest branch, for example.

2024-01-24 13:48 UTC, mrdudz commented
> the outstanding request is this comment: https://github.com/cc65/cc65/pull/2194#issuecomment-1765887453

There are also various code style issues (which is described in contributing.md)

2024-01-24 15:19 UTC, spiro-trikaliotis commented
> > never ever merge branches into a branch that's the basis for a PR.
> 
> > if you merge this PR as-is, the commit history of cc65 will be broken for eternity
> 
> No idea what you mean - i have been doing this all the time with the fptest branch, for example.

You will get the problem once you try to merge this branch. The history will be doubled and looks very "interesting".

The better approach would be to rebase your branch to master instead of merging master into it.

But this is beyond the topic of this discussion here.

2024-01-24 17:11 UTC, mrdudz commented
> The history will be doubled and looks very "interesting".

I see. the "broken" part confused me.

2024-01-24 17:13 UTC, mrdudz commented
> OK, but how does one “apply the above” patch?  That’s a broader leap than I know how to make on my own, as I’m new to git.

Make a new branch, then "git am name.patch" and commit/push the changes to that branch.

> BTW, I’m content to abandon this checkin and keep the code in my own KIM-1 repo, but figured it would be useful to others in cc-65.   Perhaps it’s easier to just revert this one and avoid the headaches.  I don’t want to cause further issues.

Oh please don't, it's a nice addition to cc65

2024-01-24 21:51 UTC, rofl0r commented
> I see. the "broken" part confused me.

you can test it on this very branch. run `git rebase -i master`, then just quit the editor that pops up with saving. git will then hickup and tell you it couldnt apply some of the duplicated commits.

> OK, but how does one “apply the above” patch?

as i said in the previous comment, using `git am filename.patch`. it will apply the patch, and create the commit from the metadata in the patch header.

2024-01-24 22:13 UTC, mrdudz commented
> you can test it on this very branch. run `git rebase -i master`, then just quit the editor that pops up with saving. git will then hickup and tell you it couldnt apply some of the duplicated commits.

rebase seems to be something else though - all i am ever doing here is merging via the web interface. And as long as that says it can be merged - i don't see the problem.

2024-01-24 22:31 UTC, rofl0r commented
> rebase seems to be something else though

rebase conceptually turns the commits of a branch into patches and reapplies them on wherever you point it to. if it hicks up even if you apply it on the same HEAD than the branch started on, it's quite a mess.
what happened here in particular is that OP merged his branch into itself "Merge branch 'KIMLife' of github.com:davepl/cc65 into KIMLife"

 > all i am ever doing here is merging via the web interface

i suppose you merge master into your branch. it's not that problematic, but it prevents a clean linear history, unlike rebase.

>And as long as that says it can be merged - i don't see the problem.

the problem happens for example if someone needs to git bisect a bug that appeared. with double commits like these here, the process cant complete without manual intervention.

2024-01-24 22:41 UTC, mrdudz commented
> the problem happens for example if someone needs to git bisect a bug that appeared. with double commits like these here, the process cant complete without manual intervention.

Perhaps you should look at the history - it has not been "clean linear" for a decade now (since it is on github? i dont know) - and no problems bisecting anything so far :)

In any case, please lets stop here - this PR has other problems that need to be fixed in the first place :)

2024-01-30 18:46 UTC, mrdudz commented
OK, since the tests passed now, it is probably ok - the most important thing for you to do now is to no more commit to this branch until it is reviewed and merged (i will have a look in the next couple days, no time to do this right now)

2024-02-02 16:39 UTC, mrdudz commented
@davepl could you delete the romfont.o file from the PR (switch to the KIMLife branch, delete it, and commit/push) - after that i can merge this

2024-02-02 17:07 UTC, rofl0r commented
/me prays that "squash and merge" option is used when @mrdudz clicks the merge button, else we have 60 commits like "fixe whitespace" added to history... (plus the confusing merge and double commits)

2024-02-02 17:21 UTC, mrdudz commented
> /me prays that "squash and merge" option is used when @mrdudz clicks the merge button, else we have 60 commits like "fixe whitespace" added to history... (plus the confusing merge and double commits, and the bins will be stored in .git as well, bloating the repo size)

Not sure what was hard to understand in my previous answer to this ranting

2024-02-02 17:30 UTC, rofl0r commented
![](https://0x0.st/HD3u.png)

i've offered to fix it, but apparently nobody gives a sh.. as long as "it works"

2024-02-03 00:47 UTC, mrdudz commented
since my time is running out again.... i applied the patch locally (and removed the file), fixed the makefile (ramfont.o was missing in the clean target) and co,mitted in 934de68 - thanks!

2024-02-03 00:47 UTC, closed without merging